[project]
name = "inputflow"
version = "0.1.0"
description = "Cross-platform keyboard and mouse sharing tool"
requires-python = ">=3.13"
dependencies = [
    "pynput>=1.8.1",
    "evdev>=1.9.2; sys_platform == 'linux'",
    "loguru>=0.7.3",
    "toml>=0.10.2",
    "click>=8.3.1",
    "zmq>=0.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]
